server:
  port: 8090

#grpc配置
grpc:
  defaultHost: 127.0.0.1:8081

#ziplin配置
zipkin:
  host: 127.0.0.1:9411
  serviceName: report-api
  traceSampler: 1.0
  enable: true

#rabbitmq配置
#默认端口说明
  #client端通信口5672
  #管理口15672 http://localhost:15672
  #server间内部通信口25672
  #erlang发现口：4369
rabbitmq:
  host: localhost
  username: report_api_mq
  password: 123456
  port: 5672


